### ISSUE TITLE
Entity in direct link title entails mis-translation

### ISSUE THREAD

**Issue by tin-pot** [mity/md4c#11]
This gets processed correctly:

    Some [direct link](http://example.com "Direct link -- ie, inline URL") here.

But when an entity reference occurs in the title text, like this:

    Some [direct link](http://example.com "Direct link &ndash; ie, inline URL") here.

the last portion of the title text (starting at the reference) gets repeated *after* the generated `<a>` element, so the output from `md2html` looks like this:

    <p>Some <a href="http://example.com" title="Direct link – ie, inline URL">dire
    ct link</a>– ie, inline URL&quot;) here.</p>

As far as I have seen, this stems from `md4c.c`, not `md2html.c`: the `&ndash;` reference is indeed transmitted twice, once embedded in the attribute text, and a second time as a `MD_TEXT_ENTITY` item itself.

On can actually observe this behaviour in [Babelmark 2][bm2], where `MD4C 0.1.1` is included as of lately.

[bm2]: <http://johnmacfarlane.net/babelmark2/?text=Some+[direct+link]%28http%3A%2F%2Fexample.com+%22Direct+link+--+ie%2C+inline+URL%22%29+here.%0A%0ASome+[direct+link]%28http%3A%2F%2Fexample.com+%22Direct+link+%26ndash%3B+ie%2C+inline+URL%22%29+here.%0A> "Babelmark 2 Example"

**Comment by mity** [comment]
Thanks for report. Fixed.

**Comment by tin-pot** [comment]
Wow! That was fast! :+1: 

Thanks!
