### ISSUE TITLE
how to use md_parse() ?

### ISSUE THREAD

**Issue by zcmimi** [mity/md4c#121]
how to use `md_parse()` ?

```cpp
string text="xxxxxxxxxxxx";
md_parse(text.c_str(),text.length(),NULL,NULL);
```

`[1]    7099 segmentation fault (core dumped)`

I can't understand when reading `md4c.h`.

What is the function of `void* userdata`？

Can you give me a use case？

Thank you so much.

**Comment by mity** [comment]
See e.g. the markdown to HTML convertor: https://github.com/mity/md4c/blob/master/src/md4c-html.c#L571

**Comment by mity** [comment]
`userdata` is a pointer to any your data, you want to pass to the callbacks. You have to provide pointer to a structure in the 3rd param, which provides function pointers to your callbacks processing the parsed data.

**Comment by zcmimi** [comment]
Thank you very much! I solve the problem successfully.
`md4c` runs very fast.
