### ISSUE TITLE
tests/normalize.py failing

### ISSUE THREAD

**Issue by protoCall7** [mity/md4c#123]
Hello,

I am in the process of porting md4c release 0.4.4 to OpenBSD, and noticed that the test infrastructure is generating stack traces with every test:

![image](https://user-images.githubusercontent.com/1879008/88600838-105aaf00-d024-11ea-9657-c9da41c17eef.png)

I am including the following patch in our package, which seems to make the tests run as intended:

```diff
$OpenBSD$

Index: test/normalize.py
--- test/normalize.py.orig
+++ test/normalize.py
@@ -14,6 +14,7 @@ from html.entities import name2codepoint
 import sys
 import re
 import cgi
+import html
 
 # Normalization code, adapted from
 # https://github.com/karlcow/markdown-testsuite/
@@ -66,7 +67,7 @@ class MyHTMLParser(HTMLParser):
                     self.output += ("=" + '"' +
                             urllib.quote(urllib.unquote(v), safe='/') + '"')
                 elif v != None:
-                    self.output += ("=" + '"' + cgi.escape(v,quote=True) + '"')
+                    self.output += ("=" + '"' + html.escape(v,quote=True) + '"')
         self.output += ">"
         self.last_tag = tag
         self.last = "starttag"
```

I wanted to make you aware that we were going to be carrying a patch. If you would prefer me to work around the broken tests in a different manner, please let me know.

Thanks!

**Comment by mity** [comment]
Thanks, applied to the upstream (with also removing the now bogus `import cgi` line).

**Comment by mity** [comment]
>  If you would prefer me to work around the broken tests in a different manner, please let me know.

I'll happily leave that burden for 0.4.4 completely on your shoulders, so anything what serves your purpose :-)

**Comment by protoCall7** [comment]
Thanks for the quick response @mity! I've now dropped the `include cgi` in my patch as well. Once the next version is released, I'll remove the patch all together.
