### ISSUE TITLE
Attributes of `CommonMark.dtd` omitted by parser

### ISSUE THREAD

**Issue by tin-pot** [mity/md4c#13]
When porting some code (which up to now used `cmark`) to MD4C I missed some information from the parser which is represented as attributes in the [_CommonMark_ DTD][dtd]:

1.  In the details for `MD_BLOCK_UL`, the information whether the list is "tight" or "loose" (attribute `tight (true|false)`.

2.  In the details for `MD_BLOCK_OL`, the information whether the list is "tight" or "loose" (attribute `tight (true|false)`, and which style of item marker was used (attribute `delimiter (period|paren)`).

Any chance to put corresponding information into `MD_BLOCK_UL_DETAIL` rsp `MD_BLOCK_OL_DETAIL`?

[dtd]: https://github.com/jgm/CommonMark/blob/master/CommonMark.dtd
  "CommonMark DTD on GitHub"

**Comment by mity** [comment]
That should be quite easy to add. I'll try to get to it tonight.

**Comment by mity** [comment]
Done.

**Comment by tin-pot** [comment]
Great - thank you!
