### ISSUE TITLE
Unmatched closing parens inside www autolinks end the link

### ISSUE THREAD

**Issue by dominickpastore** [mity/md4c#135]
It seems there is a mistake in a test case that is letting a bug through.

According to the [GFM spec](https://github.github.com/gfm/#example-625), unmatched closing parentheses fall outside www autolinks only when they do not fall inside the link. The same text is in `test/permissive-www-autolinks.txt`, but the corresponding test case doesn't actually have a mismatched parenthesis to test it. And, it turns out MD4C gets it wrong when the mismatched parenthesis is added:

Input:
```Markdown
www.google.com/search?q=(business))+ok
```

Expected output:
```HTML
<p><a href="http://www.google.com/search?q=(business))+ok">www.google.com/search?q=(business))+ok</a></p>
```

Actual output:
```HTML
<p><a href="http://www.google.com/search?q=(business)">www.google.com/search?q=(business)</a>)+ok</p>
```
(Note how `)+ok` is outside the link.)

**Comment by mity** [comment]
Will take a look at it. Thanks for reporting it.

**Comment by dominickpastore** [comment]
> parentheses fall outside www autolinks only when they do not fall inside the link.

I just realized how silly that sentence sounds, but it sounds like you understood what I meant ;)

**Comment by mity** [comment]
As long as people provide the blessed trinity Input, Expected Output and Actual Output in their reports, it's hard to misunderstand it :-)
