### ISSUE TITLE
md4c 0.4.7 test failure on apple silicon/arm

### ISSUE THREAD

**Issue by chenrui333** [mity/md4c#144]
👋  while building md4c 0.4.7, there is some issue with the test as shown below (only for 11-arm):

```
==> /opt/homebrew/Cellar/md4c/0.4.7/bin/md2html ./test_md.md
dyld: Library not loaded: @rpath/libmd4c-html.0.dylib
  Referenced from: /opt/homebrew/Cellar/md4c/0.4.7/bin/md2html
  Reason: image not found
/opt/homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
Error: md4c: failed
```

full log in here, https://github.com/Homebrew/homebrew-core/runs/1620677180
relates to https://github.com/Homebrew/homebrew-core/pull/67839

**Comment by mity** [comment]
Unfortunately, IDK what to do with this report. 

There is nothing visible in the log explaining why the md4c-html lib is missing. Actually even no log from projects's CMake or build or the installation itself. In short, it's sort of an automatic "it does not work" report.

Furthermore, I don't use homebrew, nor do I have an access to macOS right now, even less so on arm. My knowledge of quirks of that system on that platform corresponds to that.

So all I can do is keeping this report open for now, in a hope somebody else can help.

**Comment by mity** [comment]
@chenrui333 It seems to me that a later test run (https://github.com/Homebrew/homebrew-core/runs/1627755602) went ok. So the problem (whatever it was) is fixed and this can be closed?

**Comment by chenrui333** [comment]
yeah, we can leave it open and see what we can do the down the path (I probably can help with this later).

**Comment by mity** [comment]
Closing for being stale.
