### ISSUE TITLE
entity.h is not exposed as a public header

### ISSUE THREAD

**Issue by dominickpastore** [mity/md4c#160]
I'm not sure if this is intentional, but entity.h is not exposed as a public header in src/CMakeLists.txt.

I suppose this makes sense, since entity.c is only built as part of MD4C-HTML, and users of that library don't need entity.h directly. But maybe it would be a good idea to make entity.c/.h available to applications that need to implement their own renderer.

**Comment by mity** [comment]
I think https://html.spec.whatwg.org/entities.json should work as the authoritative source rather than MD4C.
