### ISSUE TITLE
make instructions look... peculiar... to me

### ISSUE THREAD

**Issue by aoloe** [mity/md4c#17]
https://github.com/mity/md4c/wiki/Building-MD4C says:

```.sh
$ cd md4c
$ mkdir build
$ cmake -G ..
$ make
```

shouldn't it be:

```sh
$ cd md4c
$ mkdir build
$ cd build
$ cmake ..
$ make
```

?

on my computer the second one works well, while the first one gives me an error that the generator .. could not be found...

**Comment by mity** [comment]
Yes. Thanks for reporting.

I've updated it.
