### ISSUE TITLE
Odd indented code block can break paragraph

### ISSUE THREAD

**Issue by dbuenzli** [mity/md4c#189]
and the spec says indented code blocks don't interrupt paragraphs

````sh
> md2html --version
0.4.8

> printf 'a\n    ```\nb' | md2html
<p>a</p>
<pre><code>b
</code></pre>

> printf 'a\n    ```\nb' | cmark  
<p>a
```
b</p>
````

Likely something fishy happening because the indented text looks like a fence: for example md2html passes [this spec test](https://spec.commonmark.org/0.30/#example-113), and it is correct if you only have two backticks or less.

**Comment by mity** [comment]
Same as #201, should be fixed.
