### ISSUE TITLE
HTML text area block not closed

### ISSUE THREAD

**Issue by step-** [mity/md4c#207]
Consider the following test subject

`````
<textarea>

*foo*

_bar_

</textarea>

baz
`````

The HTML textarea block should be closed and "baz" should be rendered as a paragraph.

cmark output:
`````<textarea>

*foo*

_bar_

</textarea>
<p>baz</p>
`````

md2html output:
`````
<textarea>

*foo*

_bar_

</textarea>

baz
`````

which, I think, indicates that the HTML block was still open when baz was parsed.

I don't need a fix. I just want to record this issue.

**Comment by mity** [comment]
Ohh yes, `<textarea>` was added in some later spec revision and clearly it has been added only into the opening condition check. I'll reorg it so that `md_is_html_block_end_condition()` reuses the same data structure to avoid such inconsistencies if that happens again.

**Comment by step-** [comment]
Excellent fix, verified on my test suite. Thank you.
