### ISSUE TITLE
Get source line number for headings

### ISSUE THREAD

**Issue by feinstaub** [mity/md4c#45]
Hello,
is it possible to retrieve the source line number for headings?
I would like to build a parser which can create a TOC with navigation feature for a markdown editor.

**Comment by mity** [comment]
It would be nice feature, but right now, it is not implemented.

It should be possible, with relatively small effort, to add some info about offsets into the callbacks.
Adding support for line numbers is doable too, but it would require more work.

If you are willing to work on either of it, I can offer you some guidance, but I do not currently enough time to implement it myself.
