### ISSUE TITLE
md2html doesn't generate HTML tables

### ISSUE THREAD

**Issue by ec1oud** [mity/md4c#55]
I tested with the example.md from https://codereview.qt-project.org/#/c/214844/ .  It simply put the raw table syntax into a paragraph:

`<p>|               | Development Tools | Programming Techniques | Graphical User Interfaces |
| ------------: | ----------------- | ---------------------- | ------------------------- |
| 9:00 - 11:00  |                     Introduction to Qt                               |||
| 11:00 - 13:00 | Using qmake       | Object-oriented Programming | Layouts in Qt        |
| 13:00 - 15:00 | Qt Designer Tutorial | Extreme Programming | Writing Custom Styles     |
| 15:00 - 17:00 | Qt Linguist and Internationalization |   |   |</p>`

This doesn't matter for Qt, and I don't have any plan to use md2html for anything ATM; but since I'm trying to add md4c to Arch AUR, if the package is to include md2html, the bugs will become noticeable when someone tries to use it for this basic purpose of generating HTML.  If it's not intended to be a serious tool (after all, there are enough MD->HTML tools to choose from), I could rather leave it out of the package though.

**Comment by ec1oud** [comment]
Anyway I pushed to AUR, so all Arch users can build the current RC from git now:

https://aur.archlinux.org/packages/md4c-git/

**Comment by mity** [comment]
It does. You have explicitly to enable any extension with some flags, here `--ftables` or `--github`. `--help` is always your friend.

**Comment by ec1oud** [comment]
right... sorry for the noise.

**Comment by mity** [comment]
no problem.

**Comment by mity** [comment]
> If it's not intended to be a serious tool (after all, there are enough MD->HTML tools to choose from), I could rather leave it out of the package though.

The truth is I wrote it mainly for testing purposes of MD4C, but it should be workable in production as well. So IMHO the main issue for being "a serious tool" is there is no man page. Not on my priority list, but opening a bug for that so that does not go out from a radar.

**Comment by ec1oud** [comment]
Sorry that wasn't a nice way to put it.  But I suspected it's meant more for testing.  It's great that it's useful for more than that.

**Comment by mity** [comment]
I don't feel offended in any way. It was completely valid question.
