### ISSUE TITLE
md2html does not have man page

### ISSUE THREAD

**Issue by mity** [mity/md4c#56]
As MD4C is currently being added into some Linux distros (see #48 or #55), md2html tool should have a better documentation, in particular man page.

**Comment by mity** [comment]
Anyone with decent English is welcome to help.

**Comment by craigbarnes** [comment]
I noticed you commented in another issue:

> I am not sure I want to get feature requests for implementing all possible output formats

Does this mean you'd prefer not to have a roff renderer and `md2man` tool contributed along with the man pages? I'd be willing to send a PR for adding man page(s) either way, but generating them from a simpler format is usually much nicer than editing roff files by hand.

**Comment by mity** [comment]
> I am not sure I want to get feature requests for implementing all possible output formats

I think my point of view has shifted somewhat since then. The main motivation for that comment originally was that I was not ready to solve the stabilization of the parser API and addition of such plugins at the same time.

But today I think we have actually reached that stage: Even the HTML renderer is likely going to become part of the official API (see #82). So I am now much more open to such idea also for other other output formats.

**Comment by craigbarnes** [comment]
@mity I've submitted a (hand-written) man page in #85.
