### ISSUE TITLE
One compilation error with gcc -Wpedantic

### ISSUE THREAD

**Issue by sgbeal** [mity/md4c#79]
$ gcc -c md4c.c -I. -Wall -Wpedantic
    md4c.c:184:14: warning: ISO C forbids forward references to ‘enum’ types [-Wpedantic]
     typedef enum MD_LINETYPE_tag MD_LINETYPE;
                  ^~~~~~~~~~~~~~~

Moving that typedef below the enum on the next line fixes it (the only `-Wpedantic` warning).

**Comment by mity** [comment]
Fixed. Thanks for reporting.
