### ISSUE TITLE
Small sizeof issue

### ISSUE THREAD

**Issue by p0nce** [mity/md4c#94]
So I've ported md4c to the D language (https://github.com/p0nce/commonmark-d) and while translating I found a little mistake here:

https://github.com/mity/md4c/blob/master/md4c/md4c.c#L1690

I think you might mean:
`sizeof(MD_REF_DEF*)` 
instead of:
`sizeof(MD_REF_DEF)` 
which takes more memory.

Same issue here: https://github.com/mity/md4c/blob/master/md4c/md4c.c#L1707

and that's all I found. Amazing library!

**Comment by mity** [comment]
Thanks for the bug report.

Nice to know about the port. I have added the link into `README.md`.
